# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10da32ec48359e1176b09bb3735e856df9087d2a9b8413c4adf29a6aef06e7e44d558b0cb064441a0c55476aac282a19dd067f151ba8a60425a681ab2d2ded8c

test:
  secret_key_base: 3dd29ee94ab10bf695b1fce611f68175e13cebe400d910d12ac818403327c1b0c1d1c5ccf3657891e0735c29b34b2d63979a4161e4f6d214bc7db00679b5bb1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
